SELECT ltrim("    MYSQL ES FACIL");

SELECT RTRIM("MYSQL ES FACIL     ");

SELECT trim("    MYSQL ES FACIL   ");

SELECT concat("mYSQL ES FACIL", " HOLA MUNDO");

SELECT UPPER("MYSQL ES UNA Base de datos interesante");

SELECT LOWER("MYSQL ES UNA BASE DE DATOS INTERESATE");

SELECT SUBSTRING('MYSQL ES UNA BASE DE DATOS INTEREASANTE', 5,10);

SELECT CONCAT(NOMBRE, " ", DNI) FROM tabla_de_clientes;

SELECT NOMBRE, CONCAT(DIRECCION_1, ' ', BARRIO, ' ', CIUDAD, ' ', ESTADO) AS COMPLETO FROM tabla_de_clientes;

SELECT CURDATE();

SELECT current_timestamp();

SELECT YEAR(current_timestamp());

SELECT month(current_timestamp());

SELECT dayname(CURRENT_TIMESTAMP());

SELECT DATEDIFF(current_timestamp(), "2001-12-29") AS DIFERENCIA_DE_DIAS;

SELECT current_timestamp() AS DIA_HOY, date_sub(CURRENT_TIMESTAMP(), INTERVAL 6 MONTH) AS RESULTADO;

SELECT distinct FECHA_VENTA;

SELECT DISTINCT FECHA_VENTA,
DAYNAME(FECHA_VENTA) AS DIA, MONTHNAME(FECHA_VENTA) AS MES, YEAR(FECHA_VENTA) AS AÑO FROM FACTURAS;

SELECT NOMBRE, TIMESTAMPDIFF(YEAR, FECHA_DE_NACIMIENTO, CURDATE()) AS    EDAD
FROM  tabla_de_clientes;

SELECT (32 +33+ 32+ 32+1)/34 AS RESULTADO;

SELECT CEILING(43.3223);

SELECT FLOOR(343.99999);

SELECT RAND() AS RESULTADO;

SELECT ROUND(254.4343, 2);

SELECT NUMERO, CANTIDAD, PRECIO FROM items_facturas;

SELECT NUMERO, CANTIDAD, PRECIO, CANTIDAD * PRECIO AS FACTURACION FROM items_facturas;

SELECT NUMERO, CANTIDAD, PRECIO, ROUND(CANTIDAD * PRECIO,2) AS FACTURACION FROM items_facturas;

SELECT YEAR(FECHA_VENTA), FLOOR(SUM(IMPUESTO * (CANTIDAD * PRECIO))) 
AS RESULTADO
FROM facturas F
INNER JOIN items_facturas IFa ON F.NUMERO = IFa.NUMERO
WHERE YEAR(FECHA_VENTA) = 2016
GROUP BY YEAR(FECHA_VENTA);



