SELECT current_timestamp() AS RESULTADO;

SELECT CONCAT("LA FECHA Y LA HORA DE HOY SON: ", CURRENT_TIMESTAMP()) AS RESULTADO;

SELECT CONCAT("LA FECHA Y EL HORARIO SON: ", DATE_FORMAT(CURRENT_TIMESTAMP(), "%y")) AS RESULTADO;
SELECT CONCAT("LA FECHA Y EL HORARIO SON: ", DATE_FORMAT(CURRENT_TIMESTAMP(), "%W, %Y, %M, A LAS %T ")) AS RESULTADO;

SELECT CONVERT(23.55, CHAR) AS RESULTADO;

SELECT substring(CONVERT(23.55, CHAR), 3, 1) AS RESULTADO;

SELECT CONCAT('El cliente ', TC.NOMBRE, ' facturó ', 
CONVERT(SUM(IFa.CANTIDAD * IFa.precio), CHAR(20))
 , ' en el año ', CONVERT(YEAR(F.FECHA_VENTA), CHAR(20))) AS FRASE FROM facturas F
INNER JOIN items_facturas IFa ON F.NUMERO = IFa.NUMERO
INNER JOIN tabla_de_clientes TC ON F.DNI = TC.DNI
WHERE YEAR(FECHA_VENTA) = 2016
GROUP BY TC.NOMBRE, YEAR(FECHA_VENTA);
